services:
  db:
    image: postgres:18
    container_name: credit-risk-db
    environment:
      POSTGRES_DB: credit_risk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: credit-risk-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: credit_risk
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data: